frequency: 50.0  # 滤波器的运行频率
use_mag: false   # 是否使用磁力计
publish_tf: false  # 是否发布 TF 坐标变换
use_imu_time: true  # 是否使用IMU的时间戳
do_bias_estimation: true  # 是否执行偏差估计
do_adaptive_gain: false  # 是否使用自适应增益

# 参数说明：

# frequency:
  # 作用：指定互补滤波器的运行频率，以Hz为单位。
  # 设置建议：这个值一般设为系统期望的滤波处理频率，50Hz 是一个常见的值。如果传感器采样率很高，可以将这个值设置得更高。

# use_mag:
  # true：启用磁力计数据。如果IMU配有磁力计，可以使用磁力计数据来帮助估计方位角（Yaw）。
  # false：禁用磁力计。适合没有磁力计的IMU，或者当磁力计数据不可靠时（例如存在磁干扰）。
  # 影响：启用磁力计后，滤波器将结合加速度计、陀螺仪和磁力计数据来估算IMU姿态。关闭磁力计时，滤波器仅使用加速度计和陀螺仪。

# publish_tf:
  # true：发布TF变换。滤波器节点会发布IMU姿态数据到TF树中。
  # false：不发布TF变换。适合只需要IMU数据但不需要变换关系的场景。
  # 影响：当TF发布启用时，可以在ROS TF树中查看IMU的姿态变化，适合机器人需要参考IMU姿态的场景。关闭时，仅处理数据而不影响坐标变换。

# use_imu_time:
  # true：使用IMU自带的时间戳。
  # false：使用系统的时间戳（ROS时间）。
  # 影响：使用IMU的时间戳可以确保IMU采样的时间准确，适合IMU内部有精确时钟的设备。使用系统时间戳则依赖ROS的采样时刻，可能会有一些延迟，但避免了IMU时钟和ROS时钟不同步的问题。

# do_bias_estimation:
  # true：启用陀螺仪偏差估计。
  # false：禁用偏差估计。
  # 影响：启用偏差估计可以自动修正陀螺仪的漂移，适合长时间运行的系统。在某些IMU设备中，陀螺仪数据会出现小幅漂移，启用此功能后，滤波器会通过估计偏差来补偿这一漂移。

# do_adaptive_gain:
  # true：启用自适应增益，滤波器会根据运动状态动态调整增益。
  # false：禁用自适应增益，使用固定增益。
  # 影响：自适应增益可以在快速运动时提高陀螺仪的权重，在静止或低速运动时提高加速度计的权重。如果系统状态变化剧烈，启用自适应增益可以提供更好的滤波效果。禁用时，滤波器使用固定的增益参数。
